# Generated by Django 5.2.4 on 2025-07-06 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('motivation', models.CharField(max_length=100, verbose_name='Что вам ближе?')),
                ('ideal_day', models.CharField(max_length=100, verbose_name='Ваш идеальный рабочий день...')),
                ('cognitive_strength', models.CharField(max_length=100, verbose_name='Что легче дается?')),
                ('self_type', models.CharField(max_length=100, verbose_name='Ты больше:')),
                ('personality_trait', models.CharField(max_length=100, verbose_name='Что вам ближе по темпераменту?')),
                ('work_environment', models.CharField(max_length=100, verbose_name='Комфортная обстановка:')),
                ('reaction_to_difficulty', models.CharField(max_length=100, verbose_name='Как вы реагируете на сложность?')),
                ('creative_or_logical', models.CharField(max_length=100, verbose_name='Что вам приятнее?')),
                ('experience', models.JSONField(blank=True, default=list, verbose_name='Опыт')),
                ('values', models.JSONField(blank=True, default=list, verbose_name='Ценности')),
                ('llm_result', models.TextField(blank=True, verbose_name='Рекомендованное направление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
